### ISSUE TITLE
Food Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-elk#3]
# User Stories
- [x] As a user, I should be able to add possible Foods to my Renaissance Fair. (#16)
- [x] As a user, I should be able to see all possible Foods at my Renaissance Fair. ( #21 ) 
- [x] As a user, I should be able to edit my spellin' mistakes on Foods. ( #17 )
- [x] As a user, I should be able to delete a crappy Food from my Renaissance Fair. (#18)
