### ISSUE TITLE
Souvenirs Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-elk#4]
# User Stories
- [x] As a user, I should be able to view all the Souvenirs in the Faire ( #23 )
- [x] As a user, I should be able to create a new souvenir. (#27)
- [x] As a user, I should be able to edit a souvenir. (#33)
- [x] As a user, I should be able to delete a souvenir (#24)
