### ISSUE TITLE
Shows Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-elk#5]
# User Stories
- [x] As a user, I should be able to add possible shows to my Renaissance Fair. (#31)
- [x] As a user, I should be able to see all possible shows at my Renaissance Fair. ( #20  )
- [x] As a user, I should be able to edit my spellin' mistakes on shows. #28 
- [x] As a user, I should be able to delete a crappy show from my Renaissance Fair #30
