### ISSUE TITLE
Staff Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-elk#6]
- [x] As a user, I should be able to add possible Staff to my Renaissance Fair. (#11 )
- [x] As a user, I should be able to see all possible Staff at my Renaissance Fair. ( #7 )
- [x] As a user, I should be able to edit my spellin' mistakes on Staff. ( #9 )
- [x] As a user, I should be able to delete a crappy Staff from my Renaissance Fair. (#10 )
